version: "3"

vars:
  IMAGE_NAME: gracefulapp:latest
  VERSION:
    sh: git describe --tags --always --dirty

tasks:
  minikube-start:
    cmds:
      - minikube start --kubernetes-version=v1.24.17

  docker-build:
    cmds:
      - eval $(minikube docker-env) && cd cmd/gracefulapp/ && docker build --platform linux/amd64 -t {{.IMAGE_NAME}} .

  docker-run:
    cmds:
      - docker run -it {{.IMAGE_NAME}}

  deploy:
    cmds:
      - kubectl config use-context minikube
      - kubectl apply -f .deploy/resource_quota.yaml
      - kubectl apply -f .deploy/deployment.yaml

  run:
    cmds:
      - go run . -namespace=default -deployment=gracefulapp

  run-release:
    cmds:
      - go run . -namespace=default -helm-release=gracefulapp

  test:
    cmds:
      - go test -race ./...

  lint:
    cmds:
      - go vet ./...
      - golangci-lint run ./...

  build:
    cmds:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags "-X main.version={{.VERSION}}" -o k8smoothie-linux-amd64
