version: "3"

vars:
  IMAGE_NAME: gracefulapp:latest

tasks:
  minikube-start:
    cmds:
      - minikube start --kubernetes-version=v1.24.17

  docker-build:
    cmds:
      - eval $(minikube docker-env) && cd cmd/gracefulapp/ && docker build --platform linux/amd64 -t {{.IMAGE_NAME}} .

  docker-run:
    cmds:
      - docker run -it {{.IMAGE_NAME}}

  deploy:
    cmds:
      - kubectl config use-context minikube
      - kubectl apply -f .deploy/resource_quota.yaml
      - kubectl apply -f .deploy/deployment.yaml

  run:
    cmds:
      - go run main.go -namespace=default -deployment=gracefulapp
